"""Shared test data for fixtures that need full Company objects.

STORY-044: Extracted from conftest.py mock_competitor_data fixture
to keep fixture body under 100 lines (code smell threshold).
"""

from solstein.domain.models import AIMaturity, Company


def make_test_companies() -> list[Company]:
    """Create 3 comprehensive test companies with all required financial fields."""
    return [
        Company(
            id="eneve_001",
            name="Eneve",
            industry="Energy Software",
            country="Germany",
            founded_year=2015,
            employees=150,
            revenue=5000000.0,
            growth_rate=0.25,
            profit_margin=0.15,
            funding_raised=2000000.0,
            valuation=50000000.0,
            github_url="https://github.com/eneve",
            website="https://eneve.de",
            description="Energy software company",
            ai_maturity=AIMaturity.STRONG,
            ai_score=7.5,
            geographic_presence=[
                "Germany",
                "France",
                "UK",
                "Netherlands",
                "Belgium",
                "Austria",
                "Switzerland",
            ],
            revenue_timeline=[
                {"year": 2020, "eur_millions": 2.0, "yoy_growth_pct": 0},
                {"year": 2021, "eur_millions": 3.0, "yoy_growth_pct": 50},
                {"year": 2022, "eur_millions": 4.0, "yoy_growth_pct": 33},
                {"year": 2023, "eur_millions": 5.0, "yoy_growth_pct": 25},
            ],
            revenue_cagr_3yr=40.0,
            revenue_cagr_5yr=25.0,
            ebitda_margin=30.0,
            recurring_revenue_pct=85.0,
            revenue_per_employee_eur_k=333.0,
            classification="Phoenix",
        ),
        Company(
            id="test_002",
            name="Test Company 2",
            industry="Energy Software",
            country="US",
            founded_year=2016,
            employees=100,
            revenue=3000000.0,
            growth_rate=0.20,
            profit_margin=0.12,
            funding_raised=1500000.0,
            valuation=30000000.0,
            github_url="https://github.com/test2",
            website="https://test2.com",
            description="Test company",
            ai_maturity=AIMaturity.MODERATE,
            ai_score=6.0,
            geographic_presence=["US", "Canada"],
            revenue_timeline=[
                {"year": 2020, "eur_millions": 1.5, "yoy_growth_pct": 0},
                {"year": 2021, "eur_millions": 2.0, "yoy_growth_pct": 33},
                {"year": 2022, "eur_millions": 2.5, "yoy_growth_pct": 25},
                {"year": 2023, "eur_millions": 3.0, "yoy_growth_pct": 20},
            ],
            revenue_cagr_3yr=20.0,
            revenue_cagr_5yr=20.0,
            ebitda_margin=15.0,
            recurring_revenue_pct=75.0,
            revenue_per_employee_eur_k=300.0,
            classification="Salt",
        ),
        Company(
            id="test_003",
            name="Test Company 3",
            industry="Energy Software",
            country="UK",
            founded_year=2017,
            employees=80,
            revenue=2000000.0,
            growth_rate=0.15,
            profit_margin=0.10,
            funding_raised=1000000.0,
            valuation=20000000.0,
            github_url="https://github.com/test3",
            website="https://test3.com",
            description="Test company",
            ai_maturity=AIMaturity.LOW,
            ai_score=5.0,
            geographic_presence=["UK", "Ireland"],
            revenue_timeline=[
                {"year": 2020, "eur_millions": 1.0, "yoy_growth_pct": 0},
                {"year": 2021, "eur_millions": 1.2, "yoy_growth_pct": 20},
                {"year": 2022, "eur_millions": 1.5, "yoy_growth_pct": 25},
                {"year": 2023, "eur_millions": 2.0, "yoy_growth_pct": 33},
            ],
            revenue_cagr_3yr=15.0,
            revenue_cagr_5yr=20.0,
            ebitda_margin=12.0,
            recurring_revenue_pct=65.0,
            revenue_per_employee_eur_k=250.0,
            classification="Lead",
        ),
    ]
