"""Corporate history report strategy.

EPIC-022: Extracted from CompanyReportGenerator for modularity.
"""

from datetime import datetime

from solstein.domain.models import Company

from .base import ReportStrategy


class CorporateHistoryStrategy(ReportStrategy):
    """Generate corporate history report."""

    @property
    def name(self) -> str:
        return "corporate_history"

    @property
    def filename_suffix(self) -> str:
        return "corporate_history"

    def generate(self, company: Company) -> str:
        """Generate corporate history report.

        Args:
            company: Company to generate report for

        Returns:
            Report content as markdown string
        """
        formatter = self.formatter

        return f"""# Corporate History - {company.name}

**Report Date**: {datetime.now().strftime("%B %Y")}
**Data Source**: SolStein Competitive Intelligence Platform
**Classification**: {company.classification or "N/A"}

---

## Executive Summary

{company.name} is a{" " if company.industry else ""}{company.industry or "company"}
{"operating from " + company.headquarters if company.headquarters else ""}.
With {formatter.format_large_number(company.financials.employees if company.financials else None)} employees and {formatter.format_currency(getattr(company.financials, "revenue", None))} revenue,
the company demonstrates a {self._classify_trajectory(company)} trajectory.

**Composite Score**: {formatter.format_score(company.composite_score)} | **Classification**: {company.classification or "N/A"}

---

## Company Profile

| Attribute | Value |
|---|---|
| Name | {company.name} |
| Industry | {company.industry or "N/A"} |
| Headquarters | {company.headquarters or "N/A"} |
| Founded | {company.founded_year or "N/A"} |
| Employees | {formatter.format_large_number(company.financials.employees if company.financials else None)} |
| Website | {company.website or "N/A"} |

---

## Financial Overview

| Metric | Value | Assessment |
|---|---|---|
| Revenue | {formatter.format_currency(getattr(company.financials, "revenue", None))} | {self._interpret_revenue(company)} |
| Growth Rate | {formatter.format_percentage(getattr(company.financials, "growth_rate", None))} | {self._interpret_growth_rate(company)} |
| Profit Margin | {formatter.format_percentage(getattr(company, "profit_margin", None))} | {self._interpret_margin(company)} |

---

*Generated by SolStein Intelligence Platform*
"""

    def _classify_trajectory(self, company: Company) -> str:
        """Classify company growth trajectory."""
        score = company.composite_score or 0
        growth = getattr(company.financials, "growth_rate", 0) or 0

        if score >= 7 and growth >= 20:
            return "🚀 Accelerating"
        elif score >= 5 and growth >= 10:
            return "📈 Growing"
        elif score >= 3:
            return "➡️ Stable"
        else:
            return "📉 Challenged"

    def _interpret_revenue(self, company: Company) -> str:
        """Interpret revenue level."""
        revenue = getattr(company.financials, "revenue", 0) or 0

        if revenue >= 100_000_000:
            return "💰 Large Enterprise"
        elif revenue >= 10_000_000:
            return "💼 Mid-Market"
        elif revenue >= 1_000_000:
            return "🏢 Growth Stage"
        else:
            return "🌱 Early Stage"

    def _interpret_growth_rate(self, company: Company) -> str:
        """Interpret growth rate."""
        growth = getattr(company.financials, "growth_rate", 0) or 0

        if growth >= 50:
            return "🚀 Hypergrowth"
        elif growth >= 20:
            return "📈 Strong Growth"
        elif growth >= 5:
            return "📊 Moderate Growth"
        else:
            return "➡️ Stable"

    def _interpret_margin(self, company: Company) -> str:
        """Interpret profit margin."""
        margin = getattr(company, "profit_margin", 0) or 0

        if margin >= 30:
            return "💎 Excellent"
        elif margin >= 15:
            return "✅ Healthy"
        elif margin >= 5:
            return "⚠️ Thin"
        else:
            return "❌ Loss-making"
