"""Deep analysis report strategy.

EPIC-022: Extracted from CompanyReportGenerator for modularity.
"""

from solstein.domain.models import Company

from .base import ReportStrategy


class DeepAnalysisStrategy(ReportStrategy):
    """Generate deep analytical report."""

    @property
    def name(self) -> str:
        return "deep_analysis"

    @property
    def filename_suffix(self) -> str:
        return "deep_analysis"

    def generate(self, company: Company) -> str:
        """Generate deep analytical report.

        Args:
            company: Company to generate report for

        Returns:
            Report content as markdown string
        """
        formatter = self.formatter
        interpreter = self.interpreter

        return f"""# Deep Analysis - {company.name}

## Executive Assessment

**Overall Rating**: {formatter.format_score(company.composite_score)}/10
**Strategic Classification**: {company.classification or "N/A"}

### Score Breakdown

| Dimension | Score | Assessment |
|---|---|---|
| Growth | {formatter.format_score(company.growth_score)} | {interpreter.interpret_growth(company.growth_score)} |
| Financial Health | {formatter.format_score(company.financial_health_score)} | {interpreter.interpret_health(company.financial_health_score)} |
| Competitive Position | {formatter.format_score(company.competitive_position_score)} | {interpreter.interpret_position(company.competitive_position_score)} |

## Strategic Analysis

### Strengths
{self._generate_strengths(company)}

### Weaknesses
{self._generate_weaknesses(company)}

### Strategic Assessment
{self._generate_strategic_assessment(company)}

---

*Generated by SolStein Intelligence Platform*
"""

    def _generate_strengths(self, company: Company) -> str:
        """Generate strengths section."""
        strengths = []

        if (company.composite_score or 0) >= 7:
            strengths.append("- Strong overall competitive position")
        if (getattr(company.financials, "growth_rate", 0) or 0) >= 20:
            strengths.append("- High revenue growth rate")
        if (getattr(company, "ai_score", 0) or 0) >= 7:
            strengths.append("- Advanced AI capabilities")

        if not strengths:
            strengths.append("- No dominant strengths identified")

        return "\n".join(strengths)

    def _generate_weaknesses(self, company: Company) -> str:
        """Generate weaknesses section."""
        weaknesses = []
        score = company.composite_score or 0

        if score < 7:
            weaknesses.append(f"- **Below Phoenix threshold** — Composite score {score:.2f}/10 (needs ≥7.0)")
        if score < 5:
            weaknesses.append(f"- **Low competitive position** — Score {score:.2f}/10 indicates significant pressure")

        growth_rate = getattr(company.financials, "growth_rate", 0) or 0
        if growth_rate < 10:
            weaknesses.append(f"- **Low growth** — {growth_rate:.1f}% growth rate (below 10% threshold)")

        ai_score = getattr(company, "ai_score", 0) or 0
        if ai_score < 5:
            weaknesses.append(f"- **Limited AI** — AI score {ai_score:.1f}/10 (below 5.0 threshold)")

        if not weaknesses:
            weaknesses.append(f"- **Strong position** — Score {score:.2f}/10 with no major weaknesses")

        return "\n".join(weaknesses)

    def _generate_strategic_assessment(self, company: Company) -> str:
        """Generate strategic assessment."""
        score = company.composite_score or 0

        if score >= 8:
            return f"{company.name} is a market leader with strong fundamentals."
        elif score >= 6:
            return f"{company.name} demonstrates solid competitive positioning."
        elif score >= 4:
            return f"{company.name} faces competitive pressures but has viable position."

        return f"{company.name} requires strategic repositioning."
