"""Financial growth report strategy.

EPIC-022: Extracted from CompanyReportGenerator for modularity.
"""

from solstein.domain.models import Company

from .base import ReportStrategy


class FinancialGrowthStrategy(ReportStrategy):
    """Generate financial growth trajectory report."""

    @property
    def name(self) -> str:
        return "financial_growth"

    @property
    def filename_suffix(self) -> str:
        return "financial_growth"

    def generate(self, company: Company) -> str:
        """Generate financial growth report.

        Args:
            company: Company to generate report for

        Returns:
            Report content as markdown string
        """
        formatter = self.formatter

        return f"""# Financial Growth Analysis - {company.name}

## Growth Trajectory

### Revenue Growth
- **Current Revenue**: {formatter.format_currency(getattr(company.financials, "revenue", None))}
- **Growth Rate**: {formatter.format_percentage(getattr(company.financials, "growth_rate", None))}
- **3-Year CAGR**: {getattr(company, "revenue_cagr_3yr", "N/A") or "N/A"}%

### Funding History
{self._format_funding_rounds(company)}

### Growth Vectors
{self._analyze_growth_vectors(company)}

---

*Generated by SolStein Intelligence Platform*
"""

    def _format_funding_rounds(self, company: Company) -> str:
        """Format funding rounds as markdown."""
        total_funding = company.total_funding_raised_eur or getattr(company, "funding_raised", None)

        if total_funding:
            total_str = f"**€{total_funding / 1e6:.0f}M total raised**"
            rounds = getattr(company, "funding_rounds", []) or []

            if not rounds:
                return f"{total_str} (detailed rounds not disclosed)"

            lines = [f"{total_str}", "", "| Round | Amount | Date |", "|---|---|---|"]
            for r in rounds[:10]:
                amount = r.get("amount", "N/A") if isinstance(r, dict) else getattr(r, "amount", "N/A")
                date = r.get("date", "N/A") if isinstance(r, dict) else getattr(r, "date", "N/A")
                round_name = r.get("round", "N/A") if isinstance(r, dict) else getattr(r, "round", "N/A")
                lines.append(f"| {round_name} | {amount} | {date} |")
            return "\n".join(lines)

        return "No funding rounds recorded"

    def _analyze_growth_vectors(self, company: Company) -> str:
        """Analyze growth vectors."""
        vectors = []

        if (getattr(company, "ai_score", 0) or 0) >= 6:
            vectors.append("- AI/ML capability expansion")
        if (getattr(company, "saas_maturity", 0) or 0) >= 6:
            vectors.append("- SaaS product scaling")
        if (getattr(company.financials, "growth_rate", 0) or 0) >= 20:
            vectors.append("- Market share expansion")

        if not vectors:
            vectors.append("- Organic growth maintenance")

        return "\n".join(vectors)
