#!/usr/bin/env python3
"""
Deep Analysis Pipeline - Integration script for Epic 1 & 5

This script demonstrates the end-to-end deep analysis pipeline:
1. Load company data from research_results.json
2. Run capability overlap analysis
3. Generate deep analysis reports with citations
4. Export markdown reports

Usage:
    PYTHONPATH=src python scripts/deep_analysis_pipeline.py --output-dir ./reports
"""

import argparse
import json
import logging

# Add src to path for imports
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from solstein.intelligence.capability_overlap import OverlapAnalyzer
from solstein.intelligence.deep_analyzer import DeepAnalysisGenerator
from solstein.intelligence.report_generator import CitedReportGenerator

try:
    from solstein.evidence.models import Claim, ConfidenceComponent, SourceType, create_claim
except ImportError:
    # Evidence system requires Neo4j which may not be available
    Claim = None
    SourceType = None
    ConfidenceComponent = None
    create_claim = None

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


def load_research_data(filepath: Path) -> list[dict]:
    """Load company data from research results JSON."""
    logger.info(f"Loading research data from {filepath}")
    with open(filepath, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("companies", [])


def create_claims_from_research(company: dict) -> list:
    """Convert company research data into claims for evidence system."""
    # For now, return empty list since evidence system requires Neo4j
    # This can be enhanced when evidence system is fully integrated
    return []


def analyze_company(
    company: dict,
    overlap_analyzer: OverlapAnalyzer,
    deep_analyzer: DeepAnalysisGenerator,
    report_gen: CitedReportGenerator,
) -> dict[str, Any]:
    """Run complete analysis on a single company."""
    company_name = company.get("company_name", "Unknown")
    logger.info(f"Analyzing: {company_name}")

    # Build company profile for analysis
    profile = {
        "company_name": company_name,
        "basic_info": company.get("basic_info", {}),
        "financials": company.get("financials", {}),
        "funding": company.get("funding", {}),
        "data_sources": company.get("data_sources", []),
    }

    # Extract source texts from company data for overlap analysis
    source_texts = []
    basic = company.get("basic_info", {})
    if basic.get("description"):
        source_texts.append(basic["description"])
    for source in company.get("data_sources", []):
        if source.get("url"):
            source_texts.append(source["url"])

    # 1. Capability overlap analysis
    overlap_result = overlap_analyzer.analyze(
        entity_id=company_name.lower().replace(" ", "_"),
        entity_name=company_name,
        source_texts=source_texts if source_texts else [basic.get("description", "")],
    )

    # 2. Generate deep analysis
    deep_analysis = deep_analyzer.generate_from_dict(company_name, profile)

    # 3. Create cited claims
    claims = create_claims_from_research(company)

    # 4. Generate markdown report directly from deep_analysis dict
    report_md = f"""# Deep Analysis - {company_name}

## Executive Summary

| Attribute | Value |
|-----------|-------|
| **Company** | {company_name} |
| **Headquarters** | {basic.get("headquarters", "Unknown")} |
| **Employees** | {basic.get("employees", "Unknown")} |
| **Founded** | {basic.get("founded_year", "Unknown")} |

## Executive Assessment

{deep_analysis["executive_assessment"]}

## Product Offering

{deep_analysis["product_offering"]}

## AI Assessment

- **AI Score:** {deep_analysis["ai_assessment"]["score"]}/10
- **Signal Level:** {deep_analysis["ai_assessment"]["signal_level"]}
- **Evidence:** {", ".join(deep_analysis["ai_assessment"]["evidence"][:5])}

## Strategic Implications

{deep_analysis["strategic_implications"]}

## Blindspot Analysis

{deep_analysis["blindspot_analysis"]}

## Key Insights

{deep_analysis["key_insights"]}

## Capability Overlap with Eneve

| Metric | Value |
|--------|-------|
| **Overall Score** | {overlap_result.overall_overlap_score:.1%} |
| **Matching Capabilities** | {overlap_result.matching_capabilities}/8 |
| **High Overlap** | {overlap_result.high_overlap_capabilities}/8 |

**Strongest Matches:** {", ".join(overlap_result.strongest_matches[:5])}

---

*Generated by Solstein Deep Analysis Pipeline*
"""

    return {
        "company_name": company_name,
        "overlap": overlap_result,
        "deep_analysis": deep_analysis,
        "claims": claims,
        "report": report_md,
    }


def main():
    parser = argparse.ArgumentParser(description="Generate deep analysis reports for Solstein companies")
    parser.add_argument(
        "--data-file",
        type=Path,
        default=Path("data/research_results/research_results.json"),
        help="Path to research results JSON",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=Path("./deep_analysis_reports"), help="Directory to save markdown reports"
    )
    parser.add_argument("--limit", type=int, default=5, help="Number of companies to analyze (default: 5)")
    parser.add_argument("--companies", nargs="+", help="Specific company names to analyze")

    args = parser.parse_args()

    # Setup output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Initialize analyzers
    logger.info("Initializing analyzers...")
    overlap_analyzer = OverlapAnalyzer()
    deep_analyzer = DeepAnalysisGenerator()
    report_gen = CitedReportGenerator()

    # Load data
    companies = load_research_data(args.data_file)
    logger.info(f"Loaded {len(companies)} companies from research data")

    # Filter companies if specific names provided
    if args.companies:
        companies = [c for c in companies if c.get("company_name") in args.companies]
        logger.info(f"Filtered to {len(companies)} specified companies")
    else:
        companies = companies[: args.limit]
        logger.info(f"Limited to first {args.limit} companies")

    # Analyze each company
    results = []
    for company in companies:
        try:
            result = analyze_company(company, overlap_analyzer, deep_analyzer, report_gen)
            results.append(result)

            # Save individual report
            company_name = result["company_name"]
            safe_name = company_name.replace(" ", "_").replace("/", "_")
            report_path = args.output_dir / f"{safe_name}_deep_analysis.md"

            with open(report_path, "w", encoding="utf-8") as f:
                f.write(result["report"])

            logger.info(f"Saved report: {report_path}")

        except Exception as e:
            logger.error(f"Failed to analyze {company.get('company_name', 'Unknown')}: {e}")
            continue

    # Generate comparison table (skipped - requires DeepAnalysisReport objects)
    # if len(results) > 1:
    #     comparison = exporter.generate_comparison_table(results)
    #     comparison_path = args.output_dir / "_comparison_table.md"
    #     with open(comparison_path, 'w', encoding='utf-8') as f:
    #         f.write(comparison)
    #     logger.info(f"Saved comparison table: {comparison_path}")
    # Generate summary
    summary_path = args.output_dir / "_analysis_summary.json"
    summary = {
        "total_analyzed": len(results),
        "companies": [r["company_name"] for r in results],
        "output_directory": str(args.output_dir),
        "reports_generated": [f"{r['company_name']}_deep_analysis.md" for r in results],
    }

    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, default=str)

    logger.info(f"Analysis complete! Generated {len(results)} reports in {args.output_dir}")
    logger.info(f"Summary saved to: {summary_path}")


if __name__ == "__main__":
    main()
