"""Company-specific report generators (EPIC-008).

Extracted from the monolithic generator.py. Contains report generation
for individual companies: corporate history, deep analysis, financial growth.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from loguru import logger

from solstein.domain.models import Company
from .base import BaseReportGenerator, ReportFormatter, ScoreInterpreter


class CompanyReportGenerator(BaseReportGenerator):
    """Generate reports for individual companies."""

    def __init__(self, output_dir: Path | None = None):
        super().__init__(output_dir)

    def generate_corporate_history(self, company: Company, output_dir: Path) -> Path:
        """Generate corporate history report."""
        formatter = self.formatter

        report = f"""# Corporate History - {company.name}

**Report Date**: {datetime.now().strftime("%B %Y")}
**Data Source**: SolStein Competitive Intelligence Platform
**Classification**: {company.classification or "N/A"}

---

## Executive Summary

{company.name} is a{" " if company.industry else ""}{company.industry or "company"}
{"operating from " + company.headquarters if company.headquarters else ""}.
With {formatter.format_large_number(company.financials.employees if company.financials else None)} employees and {formatter.format_currency(getattr(company.financials, "revenue", None))} revenue,
the company demonstrates a {self._classify_trajectory(company)} trajectory.

**Composite Score**: {formatter.format_score(company.composite_score)} | **Classification**: {company.classification or "N/A"}

---

## Company Profile

| Attribute | Value |
|---|---|
| Name | {company.name} |
| Industry | {company.industry or "N/A"} |
| Headquarters | {company.headquarters or "N/A"} |
| Founded | {company.founded_year or "N/A"} |
| Employees | {formatter.format_large_number(company.financials.employees if company.financials else None)} |
| Website | {company.website or "N/A"} |

---

## Financial Overview

| Metric | Value | Assessment |
|---|---|---|
| Revenue | {formatter.format_currency(getattr(company.financials, "revenue", None))} | {self._interpret_revenue(company)} |
| Growth Rate | {formatter.format_percentage(getattr(company.financials, "growth_rate", None))} | {self._interpret_growth_rate(company)} |
| Profit Margin | {formatter.format_percentage(getattr(company, "profit_margin", None))} | {self._interpret_margin(company)} |

---

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / f"{formatter.sanitize_filename(company.name)}_corporate_history.md"
        return self._write_report(report, output_path)

    def generate_deep_analysis(self, company: Company, output_dir: Path) -> Path:
        """Generate deep analytical report."""
        formatter = self.formatter
        interpreter = self.interpreter

        report = f"""# Deep Analysis - {company.name}

## Executive Assessment

**Overall Rating**: {formatter.format_score(company.composite_score)}/10
**Strategic Classification**: {company.classification or "N/A"}

### Score Breakdown

| Dimension | Score | Assessment |
|---|---|---|
| Growth | {formatter.format_score(company.growth_score)} | {interpreter.interpret_growth(company.growth_score)} |
| Financial Health | {formatter.format_score(company.financial_health_score)} | {interpreter.interpret_health(company.financial_health_score)} |
| Competitive Position | {formatter.format_score(company.competitive_position_score)} | {interpreter.interpret_position(company.competitive_position_score)} |

## Strategic Analysis

### Strengths
{self._generate_strengths(company)}

### Weaknesses
{self._generate_weaknesses(company)}

### Strategic Assessment
{self._generate_strategic_assessment(company)}

---

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / f"{formatter.sanitize_filename(company.name)}_deep_analysis.md"
        return self._write_report(report, output_path)

    def generate_financial_growth(self, company: Company, output_dir: Path) -> Path:
        """Generate financial growth trajectory report."""
        formatter = self.formatter

        report = f"""# Financial Growth Analysis - {company.name}

## Growth Trajectory

### Revenue Growth
- **Current Revenue**: {formatter.format_currency(getattr(company.financials, "revenue", None))}
- **Growth Rate**: {formatter.format_percentage(getattr(company.financials, "growth_rate", None))}
- **3-Year CAGR**: {getattr(company, "revenue_cagr_3yr", "N/A") or "N/A"}%

### Funding History
{self._format_funding_rounds(company)}

### Growth Vectors
{self._analyze_growth_vectors(company)}

---

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / f"{formatter.sanitize_filename(company.name)}_financial_growth.md"
        return self._write_report(report, output_path)

    # ------------------------------------------------------------------
    # Helper methods
    # ------------------------------------------------------------------

    def _classify_trajectory(self, company: Company) -> str:
        """Classify company growth trajectory."""
        score = company.composite_score or 0
        growth = getattr(company.financials, "growth_rate", 0) or 0

        if score >= 7 and growth >= 20:
            return "🚀 Accelerating"
        elif score >= 5 and growth >= 10:
            return "📈 Growing"
        elif score >= 4:
            return "➡️ Stable"
        else:
            return "📉 Challenged"

    def _interpret_revenue(self, company: Company) -> str:
        """Interpret revenue level."""
        revenue = getattr(company.financials, "revenue", 0) or 0
        if revenue >= 1000:
            return "Large enterprise"
        elif revenue >= 100:
            return "Mid-market"
        elif revenue >= 10:
            return "Growth stage"
        return "Early stage"

    def _interpret_growth_rate(self, company: Company) -> str:
        """Interpret growth rate."""
        growth = getattr(company.financials, "growth_rate", 0) or 0
        if growth >= 50:
            return "Hypergrowth"
        elif growth >= 20:
            return "Strong growth"
        elif growth >= 10:
            return "Steady growth"
        elif growth >= 0:
            return "Flat"
        return "Declining"

    def _interpret_margin(self, company: Company) -> str:
        """Interpret profit margin."""
        margin = getattr(company, "profit_margin", 0) or 0
        if margin >= 30:
            return "Highly profitable"
        elif margin >= 15:
            return "Profitable"
        elif margin >= 5:
            return "Thin margins"
        return "Unprofitable"

    def _generate_strengths(self, company: Company) -> str:
        """Generate strengths section."""
        strengths = []
        if (company.composite_score or 0) >= 7:
            strengths.append("- Strong overall competitive position")
        if (getattr(company.financials, "growth_rate", 0) or 0) >= 20:
            strengths.append("- High revenue growth rate")
        if (getattr(company, "ai_score", 0) or 0) >= 7:
            strengths.append("- Advanced AI capabilities")
        if not strengths:
            strengths.append("- No dominant strengths identified")
        return "\n".join(strengths)

    def _generate_weaknesses(self, company: Company) -> str:
        """Generate weaknesses section based on actual company data."""
        weaknesses = []
        score = company.composite_score or 0
        
        # Tier-based weakness (only for non-Phoenix companies)
        tier = getattr(company, 'tier', None)
        classification = getattr(company, 'classification', None)
        if tier and '4' in str(tier) and classification != 'Phoenix':
            weaknesses.append(f"- **Revenue-based tier ({tier})** — €{revenue:.1f}M revenue places company in Tier 4 (revenue-based tier, not performance-based classification)")
        
        # Score-based weaknesses
        if score < 7:
            weaknesses.append(f"- **Below Phoenix threshold** — Composite score {score:.2f}/10 (needs ≥7.0 for Phoenix classification)")
        if score < 5:
            weaknesses.append(f"- **Low competitive position** — Score {score:.2f}/10 indicates significant competitive pressure")
        
        # Financial weaknesses
        growth_rate = getattr(company.financials, 'growth_rate', 0) or 0
        if growth_rate < 10:
            weaknesses.append(f"- **Low growth trajectory** — {growth_rate:.1f}% growth rate (below 10% threshold)")
        
        profit_margin = getattr(company, 'profit_margin', 0) or getattr(company.financials, 'profit_margin', 0) or 0
        if profit_margin < 0:
            weaknesses.append(f"- **Unprofitable operations** — {profit_margin:.1f}% profit margin")
        elif profit_margin < 5:
            weaknesses.append(f"- **Thin margins** — {profit_margin:.1f}% profit margin (below 5% healthy threshold)")
        
        # Size/scale weaknesses (contextual based on classification)
        revenue = getattr(company.financials, 'revenue', 0) or 0
        if revenue < 10 and classification != 'Phoenix':
            weaknesses.append(f"- **Small scale** — €{revenue:.1f}M revenue limits market influence")
        elif revenue < 10 and classification == 'Phoenix':
            # For Phoenix companies, reframe as opportunity rather than weakness
            pass  # High-growth Phoenix companies can have small revenue
        
        employees = getattr(company, 'employee_count', 0) or getattr(company.financials, 'employees', 0) or 0
        if employees < 100:
            weaknesses.append(f"- **Limited workforce** — {employees} employees constrains execution capacity")
        
        # AI/Technology weaknesses
        ai_score = getattr(company, 'ai_score', 0) or 0
        if ai_score < 5:
            weaknesses.append(f"- **Limited AI capabilities** — AI score {ai_score:.1f}/10 (below 5.0 competitive threshold)")
        
        # Funding weakness (contextual)
        funding = getattr(company, 'funding_raised', 0) or getattr(company, 'total_funding_raised_eur', 0) or 0
        if funding < 5_000_000 and classification != 'Phoenix':
            weaknesses.append(f"- **Undercapitalized** — €{funding/1_000_000:.1f}M total funding (below €5M threshold)")
        elif funding < 5_000_000 and classification == 'Phoenix':
            # Phoenix companies with lower funding are efficiently capitalized
            pass
        
        if not weaknesses:
            weaknesses.append(f"- **Strong competitive position** — Composite score {score:.2f}/10 with no major identified weaknesses")
        
        return "\n".join(weaknesses)


    def _generate_strategic_assessment(self, company: Company) -> str:
        """Generate strategic assessment."""
        score = company.composite_score or 0
        if score >= 8:
            return f"{company.name} is a market leader with strong fundamentals and growth trajectory."
        elif score >= 6:
            return f"{company.name} demonstrates solid competitive positioning with room for optimization."
        elif score >= 4:
            return f"{company.name} faces competitive pressures but has viable market position."
        return f"{company.name} requires strategic repositioning to improve competitive standing."

    def _format_funding_rounds(self, company: Company) -> str:
        """Format funding rounds as markdown."""
        # Check both total_funding_raised_eur and funding_raised fields
        total_funding = company.total_funding_raised_eur or getattr(company, 'funding_raised', None)
        
        # Show total funding even when no detailed rounds are available
        if total_funding:
            total_str = f"**€{total_funding / 1e6:.0f}M total raised**"
            rounds = getattr(company, "funding_rounds", []) or []
            if not rounds:
                return f"{total_str} (detailed rounds not disclosed)"
            # Has both total and rounds - show both
            lines = [f"{total_str}", "", "| Round | Amount | Date |", "|---|---|---|"]
            for r in rounds[:10]:
                amount = r.get("amount", "N/A") if isinstance(r, dict) else getattr(r, "amount", "N/A")
                date = r.get("date", "N/A") if isinstance(r, dict) else getattr(r, "date", "N/A")
                round_name = r.get("round", "N/A") if isinstance(r, dict) else getattr(r, "round", "N/A")
                lines.append(f"| {round_name} | {amount} | {date} |")
            return "\n".join(lines)
        elif not getattr(company, "funding_rounds", None):
            return "No funding rounds recorded"
        
        # Only have rounds, no total
        lines = ["| Round | Amount | Date |", "|---|---|---|"]
        for r in company.funding_rounds[:10]:
            amount = r.get("amount", "N/A") if isinstance(r, dict) else getattr(r, "amount", "N/A")
            date = r.get("date", "N/A") if isinstance(r, dict) else getattr(r, "date", "N/A")
            round_name = r.get("round", "N/A") if isinstance(r, dict) else getattr(r, "round", "N/A")
            lines.append(f"| {round_name} | {amount} | {date} |")
        return "\n".join(lines)


    def _analyze_growth_vectors(self, company: Company) -> str:
        """Analyze growth vectors."""
        vectors = []
        if (getattr(company, "ai_score", 0) or 0) >= 6:
            vectors.append("- AI/ML capability expansion")
        if (getattr(company, "saas_maturity", 0) or 0) >= 6:
            vectors.append("- SaaS product scaling")
        if (getattr(company.financials, "growth_rate", 0) or 0) >= 20:
            vectors.append("- Market share expansion")
        if not vectors:
            vectors.append("- Organic growth maintenance")
        return "\n".join(vectors)
