"""Market overview report generator (EPIC-008).

Extracted from the monolithic generator.py. Contains market-level
reporting and competitive landscape analysis.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from loguru import logger

from solstein.domain.models import Company

from .base import BaseReportGenerator


class MarketReportGenerator(BaseReportGenerator):
    """Generate market-level overview reports."""

    def __init__(self, output_dir: Path | None = None):
        super().__init__(output_dir)

    def generate_market_overview(
        self,
        companies: list[Company],
        output_dir: Path,
        title: str = "Market Intelligence Overview",
    ) -> Path:
        """Generate comprehensive market overview report."""
        formatter = self.formatter

        if not companies:
            logger.warning("No companies provided for market overview")
            return output_dir / "market_overview_empty.md"

        # Classification distribution — normalise to title-case for
        # case-insensitive counting and include unclassified companies.
        classification_counts: dict[str, int] = {"Phoenix": 0, "Salt": 0, "Lead": 0}
        unclassified = 0
        for c in companies:
            raw = getattr(c, "classification", None)
            if raw:
                key = raw.strip().title()  # "phoenix" / "PHOENIX" → "Phoenix"
                classification_counts[key] = classification_counts.get(key, 0) + 1
            else:
                unclassified += 1

        # Top performers
        top_companies = sorted(
            companies,
            key=lambda c: c.composite_score or 0,
            reverse=True,
        )[:10]

        report = f"""# {title}

**Report Date**: {datetime.now(tz=timezone.utc).strftime("%B %Y")}
**Companies Analyzed**: {len(companies)}
**Data Source**: SolStein Competitive Intelligence Platform

---

## Executive Summary

This report analyzes {len(companies)} companies across multiple dimensions
including financial health, growth trajectory, competitive positioning, and
AI readiness.

### Key Metrics

| Metric | Value |
|---|---|
| Phoenix Tier Companies | {classification_counts.get("Phoenix", 0)} |
| Salt Tier Companies | {classification_counts.get("Salt", 0)} |
| Lead Tier Companies | {classification_counts.get("Lead", 0)} |
| Unclassified | {unclassified} |

---

## Top Performers

| Rank | Company | Score | Tier | Industry |
|---|---|---|---|---|
"""
        for i, company in enumerate(top_companies, 1):
            tier = getattr(company, "tier", None)
            tier_str = tier.value if hasattr(tier, "value") else str(tier) if tier else "N/A"
            report += f"| {i} | {company.name} | {formatter.format_score(company.composite_score)} | {tier_str} | {getattr(company, 'industry', 'N/A') or 'N/A'} |\n"

        report += """
---

## Industry Distribution

"""
        # Industry breakdown
        industries = {}
        for c in companies:
            ind = getattr(c, "industry", "Unknown") or "Unknown"
            industries[ind] = industries.get(ind, 0) + 1

        for industry, count in sorted(industries.items(), key=lambda x: x[1], reverse=True)[:10]:
            report += f"- **{industry}**: {count} companies\n"

        report += """
---

## Methodology

Companies are scored across three dimensions:
- **Growth Score**: Revenue growth, CAGR, market expansion
- **Financial Health**: Profitability, margins, funding stability
- **Competitive Position**: Market share, moat strength, AI capabilities

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / "market_overview.md"
        return self._write_report(report, output_path)

    def generate_competitive_landscape(
        self,
        reference: Company,
        competitors: list[Company],
        output_dir: Path,
    ) -> Path:
        """Generate competitive landscape analysis for a company."""
        formatter = self.formatter

        report = f"""# Competitive Landscape - {reference.name}

## Reference Company

| Attribute | Value |
|---|---|
| Name | {reference.name} |
| Composite Score | {formatter.format_score(reference.composite_score)} |
| Industry | {getattr(reference, "industry", "N/A") or "N/A"} |

## Competitive Set ({len(competitors)} companies)

| Company | Score | Industry | Relative Position |
|---|---|---|---|
"""
        ref_score = reference.composite_score or 0
        for comp in sorted(competitors, key=lambda c: c.composite_score or 0, reverse=True):
            comp_score = comp.composite_score or 0
            diff = comp_score - ref_score
            if diff > 0.5:
                position = f"+{diff:.1f} Ahead"
            elif diff < -0.5:
                position = f"{diff:.1f} Behind"
            else:
                position = "~ Parity"
            score_str = f"{comp_score:.2f}" if comp_score else "N/A"
            report += (
                f"| {comp.name} | {score_str} | {getattr(comp, 'industry', 'N/A') or 'N/A'} | {position} |\n"
            )

        report += """
---

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / f"{formatter.sanitize_filename(reference.name)}_competitive_landscape.md"
        return self._write_report(report, output_path)
