"""Market overview report generator (EPIC-008).

Extracted from the monolithic generator.py. Contains market-level
reporting and competitive landscape analysis.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from loguru import logger

from solstein.domain.models import Company
from .base import BaseReportGenerator, ReportFormatter, ScoreInterpreter


class MarketReportGenerator(BaseReportGenerator):
    """Generate market-level overview reports."""

    def __init__(self, output_dir: Path | None = None):
        super().__init__(output_dir)

    def generate_market_overview(
        self,
        companies: list[Company],
        output_dir: Path,
        title: str = "Market Intelligence Overview",
    ) -> Path:
        """Generate comprehensive market overview report."""
        formatter = self.formatter
        interpreter = self.interpreter

        if not companies:
            logger.warning("No companies provided for market overview")
            return output_dir / "market_overview_empty.md"

        # Calculate aggregate statistics
        avg_score = formatter.avg([c.composite_score or 0 for c in companies])
        avg_growth = formatter.avg(
            [getattr(c.financials, "growth_rate", 0) or 0 for c in companies if hasattr(c, "financials")]
        )

        # Tier distribution
        tier_counts = {}
        for c in companies:
            tier = getattr(c, "tier", None)
            tier_str = tier.value if hasattr(tier, "value") else str(tier) if tier else "Unknown"
            tier_counts[tier_str] = tier_counts.get(tier_str, 0) + 1

        # Top performers
        top_companies = sorted(
            companies,
            key=lambda c: c.composite_score or 0,
            reverse=True,
        )[:10]

        report = f"""# {title}

**Report Date**: {datetime.now().strftime("%B %Y")}
**Companies Analyzed**: {len(companies)}
**Data Source**: SolStein Competitive Intelligence Platform

---

## Executive Summary

This report analyzes {len(companies)} companies across multiple dimensions
including financial health, growth trajectory, competitive positioning, and
AI readiness.

### Key Metrics

| Metric | Value |
|---|---|
| Average Composite Score | {avg_score:.2f}/10 |
| Average Growth Rate | {formatter.format_percentage(avg_growth)} |
| Phoenix Tier Companies | {tier_counts.get("Phoenix", 0)} |
| Salt Tier Companies | {tier_counts.get("Salt", 0)} |
| Lead Tier Companies | {tier_counts.get("Lead", 0)} |

---

## Top Performers

| Rank | Company | Score | Tier | Industry |
|---|---|---|---|---|
"""
        for i, company in enumerate(top_companies, 1):
            tier = getattr(company, "tier", None)
            tier_str = tier.value if hasattr(tier, "value") else str(tier) if tier else "N/A"
            report += f"| {i} | {company.name} | {company.composite_score or 'N/A'} | {tier_str} | {getattr(company, 'industry', 'N/A') or 'N/A'} |\n"

        report += """
---

## Industry Distribution

"""
        # Industry breakdown
        industries = {}
        for c in companies:
            ind = getattr(c, "industry", "Unknown") or "Unknown"
            industries[ind] = industries.get(ind, 0) + 1

        for industry, count in sorted(industries.items(), key=lambda x: x[1], reverse=True)[:10]:
            report += f"- **{industry}**: {count} companies\n"

        report += """
---

## Methodology

Companies are scored across three dimensions:
- **Growth Score**: Revenue growth, CAGR, market expansion
- **Financial Health**: Profitability, margins, funding stability
- **Competitive Position**: Market share, moat strength, AI capabilities

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / "market_overview.md"
        return self._write_report(report, output_path)

    def generate_competitive_landscape(
        self,
        reference: Company,
        competitors: list[Company],
        output_dir: Path,
    ) -> Path:
        """Generate competitive landscape analysis for a company."""
        formatter = self.formatter

        report = f"""# Competitive Landscape - {reference.name}

## Reference Company

| Attribute | Value |
|---|---|
| Name | {reference.name} |
| Composite Score | {reference.composite_score or "N/A"} |
| Industry | {getattr(reference, "industry", "N/A") or "N/A"} |

## Competitive Set ({len(competitors)} companies)

| Company | Score | Industry | Relative Position |
|---|---|---|---|
"""
        ref_score = reference.composite_score or 0
        for comp in sorted(competitors, key=lambda c: c.composite_score or 0, reverse=True):
            comp_score = comp.composite_score or 0
            diff = comp_score - ref_score
            if diff > 0.5:
                position = f"+{diff:.1f} Ahead"
            elif diff < -0.5:
                position = f"{diff:.1f} Behind"
            else:
                position = "~ Parity"
            report += (
                f"| {comp.name} | {comp_score or 'N/A'} | {getattr(comp, 'industry', 'N/A') or 'N/A'} | {position} |\n"
            )

        report += """
---

*Generated by SolStein Intelligence Platform*
"""
        output_path = output_dir / f"{formatter.sanitize_filename(reference.name)}_competitive_landscape.md"
        return self._write_report(report, output_path)
