"""Improved Excel exporter for SolStein dashboards.

EPIC-005: Excel Export Improvements
EPIC-022: Refactored to use modular components

This module provides a refactored, cleaner implementation of the Excel export
functionality with proper error handling and consistent formatting.

Components are now modularized in the excel/ package:
- styles.py: Layout constants, colors, and styling
- utils.py: Utility functions for data formatting
- sheets.py: Sheet generator functions
"""

import json
from pathlib import Path
from typing import Any

from loguru import logger
from openpyxl import Workbook

from ..config import Settings
from ..domain.models import Company
from .excel.sheets import (
    add_executive_summary,
    add_financial_intelligence,
    add_market_rankings,
)
from .excel.sheets_extended import (
    add_advanced_data,
    add_revenue_history,
)
from .excel.styles import ExcelStyles


class ImprovedExcelExporter:
    """Improved Excel exporter with modular sheet generators.

    EPIC-022: Refactored to use Strategy Pattern for sheet generation.
    Each sheet type is generated by a separate function for modularity.
    """

    def __init__(self, template_path: Path | None = None):
        """Initialize the Excel exporter.

        Args:
            template_path: Optional path to Excel template
        """
        self.settings = Settings.load()
        self.styles = ExcelStyles()
        self.template_path = template_path

    def create_dashboard(
        self,
        profiles: list[Company],
        output_path: Path,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        """Create a complete Excel dashboard.

        Args:
            profiles: List of company profiles to include
            output_path: Path to save the Excel file
        """
        logger.info(f"Creating Excel dashboard with {len(profiles)} companies")

        try:
            # Create workbook
            wb = Workbook()

            # Remove default sheet
            if wb.active is not None:
                wb.remove(wb.active)

            # Create sheets using modular generators
            # Executive Summary
            ws_summary = wb.create_sheet("Executive Summary")
            add_executive_summary(ws_summary, self.styles, profiles)

            # Market Rankings
            ws_rankings = wb.create_sheet("Market Rankings")
            add_market_rankings(ws_rankings, self.styles, profiles)

            # Financial Intelligence
            ws_financial = wb.create_sheet("Financial Intelligence")
            add_financial_intelligence(ws_financial, self.styles, profiles)

            # STORY-125: Revenue History (time-series data)
            ws_revenue = wb.create_sheet("Revenue History")
            add_revenue_history(ws_revenue, self.styles, profiles)

            # STORY-125: Advanced Data (corporate structure, provenance, notes)
            ws_advanced = wb.create_sheet("Advanced Data")
            add_advanced_data(ws_advanced, self.styles, profiles)

            if metadata:
                self._add_metadata_sheet(wb, metadata)

            # Save workbook
            output_path.parent.mkdir(parents=True, exist_ok=True)
            wb.save(output_path)

            logger.info(f"Excel dashboard saved to {output_path}")

        except Exception as e:
            logger.error(f"Failed to create Excel dashboard: {e}")
            raise

    def _add_metadata_sheet(self, workbook: Workbook, metadata: dict[str, Any]) -> None:
        worksheet = workbook.create_sheet("Export Metadata")
        worksheet.append(["key", "value"])
        for key, value in metadata.items():
            if isinstance(value, (dict, list)):
                rendered = json.dumps(value, indent=2, sort_keys=True)
            else:
                rendered = value
            worksheet.append([key, rendered])
