"""Financial growth report generator for Epic 2.

Generates markdown reports from FinancialIntelligence analysis.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .financial_models import FinancialIntelligence, FundingRound, GrowthVector


class FinancialGrowthReportGenerator:
    """Generate financial growth analysis reports."""

    def __init__(self):
        self.currency_format = "€{:.1f}M"

    def generate(
        self,
        company_name: str,
        financial_intelligence: "FinancialIntelligence",
    ) -> str:
        """Generate complete financial growth report.

        Args:
            company_name: Company name
            financial_intelligence: Financial intelligence data

        Returns:
            Markdown report as string
        """
        sections = [
            self._generate_header(company_name),
            self._generate_growth_trajectory(financial_intelligence),
            self._generate_funding_intelligence(financial_intelligence),
            self._generate_growth_vectors(financial_intelligence),
            self._generate_projection(financial_intelligence),
            self._generate_health_assessment(financial_intelligence),
            self._generate_footer(),
        ]

        return "\n\n".join(sections)

    def generate_and_save(
        self,
        company_name: str,
        financial_intelligence: "FinancialIntelligence",
        output_path: Path,
    ) -> Path:
        """Generate and save report to file.

        Args:
            company_name: Company name
            financial_intelligence: Financial intelligence data
            output_path: Output file path

        Returns:
            Path to saved file
        """
        report = self.generate(company_name, financial_intelligence)
        output_path.write_text(report, encoding="utf-8")
        return output_path

    def _generate_header(self, company_name: str) -> str:
        """Generate report header."""
        return f"""# Financial Growth Analysis - {company_name}

*Generated by Solstein Financial Intelligence Module (Epic 2)*

---"""

    def _generate_growth_trajectory(self, fi: "FinancialIntelligence") -> str:
        """Generate growth trajectory section."""
        sections = ["## Growth Trajectory"]

        # Key metrics
        sections.append("")
        sections.append("### Key Metrics")

        # Revenue
        if fi.revenue_timeline:
            latest = fi.revenue_timeline[-1]
            sections.append(f"- **Current Revenue**: {self.currency_format.format(latest.revenue)}")

        # Growth rates
        if fi.cagr_3yr is not None:
            sections.append(f"- **3-Year CAGR**: {fi.cagr_3yr}%")
        if fi.cagr_5yr is not None:
            sections.append(f"- **5-Year CAGR**: {fi.cagr_5yr}%")

        # Trajectory
        trajectory_emoji = {
            "accelerating": "📈",
            "steady": "➡️",
            "decelerating": "📉",
            "declining": "⬇️",
            "unknown": "❓",
        }
        emoji = trajectory_emoji.get(fi.growth_trajectory.value, "❓")
        sections.append(f"- **Trajectory**: {emoji} {fi.growth_trajectory.value.title()}")
        sections.append(f"- **Consistency Score**: {fi.growth_consistency_score}/10")

        # Revenue timeline table
        if fi.revenue_timeline:
            sections.append("")
            sections.append("### Revenue Timeline")
            sections.append("")
            sections.append("| Year | Revenue | Source | Confidence |")
            sections.append("|------|---------|--------|------------|")
            for point in sorted(fi.revenue_timeline, key=lambda x: x.year):
                sections.append(
                    f"| {point.year} | {self.currency_format.format(point.revenue)} | "
                    f"{point.source} | {point.confidence.value} |"
                )

        # Narrative
        if fi.trajectory_narrative:
            sections.append("")
            sections.append("### Assessment")
            sections.append(fi.trajectory_narrative)

        return "\n".join(sections)

    def _generate_funding_intelligence(self, fi: "FinancialIntelligence") -> str:
        """Generate funding intelligence section."""
        sections = ["## Funding Intelligence"]

        # Summary metrics
        sections.append("")
        sections.append("### Funding Summary")

        if fi.total_funding_raised:
            sections.append(f"- **Total Raised**: {self.currency_format.format(fi.total_funding_raised)}")

        sections.append(f"- **Rounds Completed**: {len(fi.funding_rounds_enhanced)}")
        sections.append(f"- **Investor Quality Score**: {fi.investor_quality_score}/10")
        sections.append(f"- **Funding Velocity**: {fi.funding_velocity.value.title()}")

        if fi.runway_estimate_months:
            runway_emoji = (
                "🟢" if fi.runway_estimate_months >= 24 else "🟡" if fi.runway_estimate_months >= 12 else "🔴"
            )
            sections.append(f"- **Estimated Runway**: {runway_emoji} {fi.runway_estimate_months} months")

        if fi.last_funding_date:
            sections.append(f"- **Last Funding**: {fi.last_funding_date}")

        # Funding rounds table
        if fi.funding_rounds_enhanced:
            sections.append("")
            sections.append("### Funding History")
            sections.append("")

            # Check if we have detailed round data or just summary
            has_detailed_rounds = any(
                r.date is not None or r.lead_investor is not None
                for r in fi.funding_rounds_enhanced
            )

            if has_detailed_rounds:
                sections.append("| Round | Amount | Date | Lead Investor | Valuation |")
                sections.append("|-------|--------|------|---------------|-----------|")

                for round_data in fi.funding_rounds_enhanced[:10]:  # Top 10
                    amount_str = self.currency_format.format(round_data.amount) if round_data.amount else "Undisclosed"
                    date_str = round_data.date.isoformat() if round_data.date else "Unknown"
                    lead_str = round_data.lead_investor or "Unknown"
                    val_str = self.currency_format.format(round_data.valuation) if round_data.valuation else "Undisclosed"

                    sections.append(f"| {round_data.round_name} | {amount_str} | {date_str} | {lead_str} | {val_str} |")
            else:
                # Summary only - no detailed table
                sections.append(
                    "*Detailed funding round data not available. "
                    f"Total of {len(fi.funding_rounds_enhanced)} funding event(s) recorded.*"
                )
        # Narrative
        if fi.funding_narrative:
            sections.append("")
            sections.append("### Assessment")
            sections.append(fi.funding_narrative)

        return "\n".join(sections)

    def _generate_growth_vectors(self, fi: "FinancialIntelligence") -> str:
        """Generate growth vectors section."""
        sections = ["## Growth Vectors"]

        if not fi.primary_growth_vectors:
            sections.append("")
            sections.append("*No growth vectors identified from available data.*")
            return "\n".join(sections)

        # Summary
        sections.append("")
        sections.append(f"**{len(fi.primary_growth_vectors)} growth vectors identified**")

        # Vector details
        for i, vector in enumerate(fi.primary_growth_vectors[:5], 1):
            sections.append("")

            # Header with confidence indicator
            confidence_emoji = "🟢" if vector.confidence >= 0.7 else "🟡" if vector.confidence >= 0.4 else "🟠"
            impact_emoji = (
                "🚀" if vector.estimated_impact == "high" else "📊" if vector.estimated_impact == "medium" else "📋"
            )

            sections.append(f"### {i}. {vector.name} {confidence_emoji}")
            sections.append(f"- **Confidence**: {vector.confidence:.0%}")
            sections.append(f"- **Estimated Impact**: {impact_emoji} {vector.estimated_impact.title()}")

            if vector.evidence:
                sections.append("- **Evidence**:")
                for evidence in vector.evidence[:3]:
                    sections.append(f"  - {evidence}")

        return "\n".join(sections)

    def _generate_projection(self, fi: "FinancialIntelligence") -> str:
        """Generate projection section."""
        sections = ["## 12-Month Projection"]

        if fi.projected_revenue_12mo is None:
            sections.append("")
            sections.append("*Insufficient data for revenue projection.*")
            return "\n".join(sections)

        # Confidence indicator
        confidence_emoji = {
            "high": "🟢",
            "medium": "🟡",
            "low": "🟠",
            "unknown": "⚪",
        }.get(fi.projection_confidence.value, "⚪")

        sections.append("")
        sections.append("### Revenue Forecast")
        sections.append(f"- **Projected Revenue**: {self.currency_format.format(fi.projected_revenue_12mo)}")
        sections.append(f"- **Confidence Level**: {confidence_emoji} {fi.projection_confidence.value.title()}")

        # Rationale
        if fi.projection_rationale:
            sections.append("")
            sections.append("### Rationale")
            sections.append(fi.projection_rationale)

        return "\n".join(sections)

    def _generate_health_assessment(self, fi: "FinancialIntelligence") -> str:
        """Generate health assessment section."""
        sections = ["## Financial Health Assessment"]

        # Overall score
        if fi.financial_health_score is not None:
            score = fi.financial_health_score
            score_emoji = "🟢" if score >= 7 else "🟡" if score >= 5 else "🔴"
            sections.append("")
            sections.append(f"### Overall Score: {score_emoji} {score}/10")

        # Assessment narrative
        if fi.health_assessment:
            sections.append("")
            sections.append(fi.health_assessment)

        # Strengths
        if fi.key_strengths:
            sections.append("")
            sections.append("### Key Strengths")
            for strength in fi.key_strengths:
                sections.append(f"- ✅ {strength}")

        # Risks
        if fi.key_risks:
            sections.append("")
            sections.append("### Key Risks")
            for risk in fi.key_risks:
                sections.append(f"- ⚠️ {risk}")

        return "\n".join(sections)

    def _generate_footer(self) -> str:
        """Generate report footer."""
        return """---

*Report generated by Solstein Financial Intelligence Module*

**Methodology**: This analysis combines revenue trajectory analysis, funding intelligence,
growth vector detection, and predictive modeling to provide a comprehensive view of
financial growth potential. Confidence levels reflect data availability and consistency.

**Data Sources**: Crunchbase, Companies House, LinkedIn, news signals, and company disclosures."""


class BatchFinancialReportGenerator(FinancialGrowthReportGenerator):
    """Generate financial reports for multiple companies."""

    def __init__(self):
        self.generator = FinancialGrowthReportGenerator()

    def generate_batch(
        self,
        results: list[tuple[str, "FinancialIntelligence"]],
        output_dir: Path,
    ) -> list[Path]:
        """Generate reports for multiple companies.

        Args:
            results: List of (company_name, financial_intelligence) tuples
            output_dir: Directory to save reports

        Returns:
            List of saved file paths
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        saved_paths = []

        for company_name, fi in results:
            # Create safe filename
            safe_name = "".join(c if c.isalnum() else "_" for c in company_name).strip("_")

            output_path = output_dir / f"{safe_name}_financial_growth.md"

            try:
                path = self.generator.generate_and_save(company_name, fi, output_path)
                saved_paths.append(path)
            except Exception as e:
                print(f"Error generating report for {company_name}: {e}")

        return saved_paths

    def generate_summary_table(
        self,
        results: list[tuple[str, "FinancialIntelligence"]],
    ) -> str:
        """Generate summary table of all analyses.

        Args:
            results: List of (company_name, financial_intelligence) tuples

        Returns:
            Markdown table as string
        """
        lines = [
            "# Financial Growth Summary",
            "",
            "| Company | Revenue | CAGR 3Yr | Trajectory | Funding | Health Score |",
            "|---------|---------|----------|------------|---------|--------------|",
        ]

        for company_name, fi in results:
            # Revenue
            revenue = f"€{fi.revenue_timeline[-1].revenue:.1f}M" if fi.revenue_timeline else "N/A"

            # CAGR
            cagr = f"{fi.cagr_3yr}%" if fi.cagr_3yr else "N/A"

            # Trajectory
            traj = fi.growth_trajectory.value.title()

            # Funding
            funding = f"€{fi.total_funding_raised:.1f}M" if fi.total_funding_raised else "N/A"

            # Health
            health = f"{fi.financial_health_score}/10" if fi.financial_health_score else "N/A"

            lines.append(f"| {company_name} | {revenue} | {cagr} | {traj} | {funding} | {health} |")

        return "\n".join(lines)



    async def generate_narratives(
        self,
        company_name: str,
        financial_intelligence: "FinancialIntelligence",
        industry: str = "energy software",
        region: str = "Europe",
    ) -> dict[str, str]:
        from .narrative_synthesis import NarrativeContext, NarrativeSynthesisEngine
        context = NarrativeContext(
            company_name=company_name,
            industry=industry,
            region=region,
            data_quality="medium",
        )
        engine = NarrativeSynthesisEngine()
        return await engine.generate_financial_thesis(financial_intelligence, context)

    def generate_with_narratives(
        self,
        company_name: str,
        financial_intelligence: "FinancialIntelligence",
        narratives: dict[str, str],
    ) -> str:
        sections = [
            self._generate_header(company_name),
            narratives.get("investment_thesis", ""),
            self._generate_growth_trajectory(financial_intelligence),
            self._generate_funding_intelligence(financial_intelligence),
            self._generate_growth_vectors(financial_intelligence),
            self._generate_projection(financial_intelligence),
            narratives.get("strategic_recommendations", ""),
            narratives.get("competitive_context", ""),
            self._generate_health_assessment(financial_intelligence),
            self._generate_footer(),
        ]
        return "\n\n".join(sections)
