"""Genealogy report generator for Epic 3."""

from pathlib import Path

from .genealogy_models import CorporateGenealogy


class GenealogyReportGenerator:
    def generate(self, genealogy: CorporateGenealogy) -> str:
        lines = [
            f"# Corporate Genealogy Analysis - {genealogy.company_name}",
            "",
            "*Generated by Solstein Corporate Genealogy Tracker (Epic 3)*",
            "",
            "---",
            "",
            "## Ownership Structure",
            "",
        ]

        lines.extend(self._format_ownership(genealogy))
        lines.append("")
        lines.extend(self._format_transactions(genealogy))
        lines.append("")
        lines.extend(self._format_subsidiaries(genealogy))
        lines.append("")
        lines.extend(self._format_strategic_analysis(genealogy))
        lines.append("")
        lines.extend(self._format_footer())

        return "\n".join(lines)

    def _format_ownership(self, genealogy: CorporateGenealogy) -> list[str]:
        lines = [
            f"**Ownership Type:** {genealogy.ownership_type.replace('_', ' ').title()}",
            "",
        ]

        if genealogy.current_owner:
            lines.extend(
                [
                    f"**Current Owner:** {genealogy.current_owner}",
                    "",
                ]
            )

        if genealogy.ownership_history:
            lines.extend(
                [
                    "### Ownership History",
                    "",
                    "| Owner | Stake | Date |",
                    "|-------|-------|------|",
                ]
            )
            for stake in genealogy.ownership_history[:5]:
                pct = f"{stake.percentage}%" if stake.percentage else "Unknown"
                dt = stake.acquisition_date.isoformat() if stake.acquisition_date else "Unknown"
                lines.append(f"| {stake.owner_name} | {pct} | {dt} |")
            lines.append("")

        return lines

    def _format_transactions(self, genealogy: CorporateGenealogy) -> list[str]:
        lines = [
            "## M&A Activity Summary",
            "",
            f"- **Acquisitions:** {genealogy.acquisition_count}",
            f"- **Divestitures:** {genealogy.divestiture_count}",
            f"- **Mergers:** {genealogy.merger_count}",
            "",
        ]

        if genealogy.total_acquisition_value:
            lines.append(f"- **Total Acquisition Value:** €{genealogy.total_acquisition_value:.1f}M")
        if genealogy.total_divestiture_value:
            lines.append(f"- **Total Divestiture Value:** €{genealogy.total_divestiture_value:.1f}M")

        lines.append("")

        if genealogy.transactions:
            lines.extend(
                [
                    "### Transaction History",
                    "",
                    "| Date | Type | Target | Acquirer | Value |",
                    "|------|------|--------|----------|-------|",
                ]
            )

            for t in genealogy.transactions[:10]:
                date_str = t.date.isoformat() if t.date else "Unknown"
                value_str = f"€{t.value_eur_millions:.1f}M" if t.value_eur_millions else "Undisclosed"
                acquirer = t.acquirer_name or "Unknown"
                lines.append(
                    f"| {date_str} | {t.transaction_type.value.title()} | {t.target_name} | {acquirer} | {value_str} |"
                )
            lines.append("")

        return lines

    def _format_subsidiaries(self, genealogy: CorporateGenealogy) -> list[str]:
        if not genealogy.subsidiaries:
            return []

        lines = [
            "## Subsidiaries & Affiliates",
            "",
            f"**Total Subsidiaries:** {len(genealogy.subsidiaries)}",
            "",
            "| Name | Relationship | Geography | Focus |",
            "|------|--------------|-----------|-------|",
        ]

        for sub in genealogy.subsidiaries[:10]:
            geo = sub.geography or "Unknown"
            focus = sub.business_focus or "Unknown"
            lines.append(f"| {sub.name} | {sub.relationship_type} | {geo} | {focus} |")

        lines.append("")
        return lines

    def _format_strategic_analysis(self, genealogy: CorporateGenealogy) -> list[str]:
        lines = [
            "## Strategic Analysis",
            "",
            "### Genealogy Narrative",
            "",
            genealogy.genealogy_narrative,
            "",
        ]

        if genealogy.strategic_implications:
            lines.extend(
                [
                    "### Strategic Implications",
                    "",
                    genealogy.strategic_implications,
                    "",
                ]
            )

        if genealogy.integration_risks:
            lines.extend(
                [
                    "### Integration Risks",
                    "",
                ]
            )
            for risk in genealogy.integration_risks:
                lines.append(f"- ⚠️ {risk}")
            lines.append("")

        return lines

    def _format_footer(self) -> list[str]:
        return [
            "---",
            "",
            "*Report generated by Solstein Corporate Genealogy Tracker*",
            "",
            "**Methodology:** M&A activity detection uses signal-based keyword analysis ",
            "combined with ownership pattern recognition. Data sourced from company disclosures, ",
            "news reports, and regulatory filings.",
        ]


class BatchGenealogyReportGenerator:
    def __init__(self):
        self.generator = GenealogyReportGenerator()

    def generate_batch(
        self,
        results: list[tuple[str, CorporateGenealogy]],
        output_dir: Path,
    ) -> list[Path]:
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []

        for company_name, genealogy in results:
            safe_name = company_name.replace(" ", "_")
            report_path = output_dir / f"{safe_name}_genealogy.md"
            report_content = self.generator.generate(genealogy)
            report_path.write_text(report_content, encoding="utf-8")
            paths.append(report_path)

        return paths



    async def generate_narratives(
        self,
        genealogy: CorporateGenealogy,
        industry: str = "energy software",
        region: str = "Europe",
    ) -> dict[str, str]:
        from .narrative_synthesis import NarrativeContext, NarrativeSynthesisEngine
        context = NarrativeContext(
            company_name=genealogy.company_name,
            industry=industry,
            region=region,
            data_quality="medium",
        )
        engine = NarrativeSynthesisEngine()
        return await engine.generate_genealogy_narrative(genealogy, context)

    def generate_with_narratives(
        self, genealogy: CorporateGenealogy, narratives: dict[str, str]
    ) -> str:
        lines = [
            f"# Corporate Genealogy Analysis - {genealogy.company_name}",
            "",
            "*Generated by Solstein Corporate Genealogy Tracker (Epic 3)*",
            "",
            "---",
            "",
            narratives.get("ownership_narrative", ""),
            "",
            "## Ownership Structure",
            "",
        ]
        lines.extend(self._format_ownership(genealogy))
        lines.append("")
        lines.extend(self._format_transactions(genealogy))
        lines.append("")
        lines.append(narratives.get("ma_narrative", ""))
        lines.append("")
        lines.extend(self._format_subsidiaries(genealogy))
        lines.append("")
        lines.extend(self._format_strategic_analysis(genealogy))
        lines.append("")
        lines.extend(self._format_footer())
        return "\n".join(lines)