"""Protocol mapping report generator for Epic 4."""

from pathlib import Path

from .protocol_models import MarketMaturity, ProtocolMap


class ProtocolReportGenerator:
    def generate(self, protocol_map: ProtocolMap) -> str:
        lines = [
            f"# Market Protocol Mapping - {protocol_map.company_name}",
            "",
            "*Generated by Solstein Market Protocol Mapper (Epic 4)*",
            "",
            "---",
            "",
            "## Market Presence Overview",
            "",
        ]

        lines.extend(self._format_overview(protocol_map))
        lines.append("")
        lines.extend(self._format_markets(protocol_map))
        lines.append("")
        lines.extend(self._format_strategy(protocol_map))
        lines.append("")
        lines.extend(self._format_footer())

        return "\n".join(lines)

    def _format_overview(self, protocol_map: ProtocolMap) -> list[str]:
        lines = [
            f"- **Total Countries:** {protocol_map.total_countries}",
            f"- **Total Protocols:** {protocol_map.total_protocols}",
            f"- **Geographic Diversification:** {protocol_map.geographic_diversification_score}/10",
            f"- **Protocol Complexity:** {protocol_map.protocol_complexity_score}/10",
            "",
        ]

        if protocol_map.primary_markets:
            lines.append(f"- **Primary Markets:** {', '.join(protocol_map.primary_markets)}")

        if protocol_map.emerging_markets:
            lines.append(f"- **Emerging Markets:** {', '.join(protocol_map.emerging_markets)}")

        lines.append("")
        return lines

    def _format_markets(self, protocol_map: ProtocolMap) -> list[str]:
        if not protocol_map.markets:
            return ["*No market presence detected from available data.*", ""]

        lines = ["## Country-by-Country Analysis", ""]

        for market in protocol_map.markets:
            maturity_emoji = {
                MarketMaturity.MATURE: "🟢",
                MarketMaturity.DEVELOPING: "🟡",
                MarketMaturity.EMERGING: "🔵",
                MarketMaturity.RESTRICTED: "🔴",
            }.get(market.market_maturity, "⚪")

            lines.extend(
                [
                    f"### {maturity_emoji} {market.country_name} ({market.country_code})",
                    "",
                    f"**Market Maturity:** {market.market_maturity.value.title()}",
                    "",
                    "**Active Protocols:**",
                    "",
                ]
            )

            for presence in market.protocols:
                status = "✅" if presence.is_active else "⬜"
                lines.append(
                    f"- {status} **{presence.protocol.protocol_name}** "
                    f"({presence.protocol.protocol_type.value.title()})"
                )

            lines.append("")

        return lines

    def _format_strategy(self, protocol_map: ProtocolMap) -> list[str]:
        lines = [
            "## Strategic Analysis",
            "",
            "### Market Entry Strategy",
            "",
            protocol_map.market_entry_strategy,
            "",
        ]

        if protocol_map.expansion_opportunities:
            lines.extend(
                [
                    "### Expansion Opportunities",
                    "",
                ]
            )
            for opp in protocol_map.expansion_opportunities:
                lines.append(f"- 💡 {opp}")
            lines.append("")

        if protocol_map.regulatory_risks:
            lines.extend(
                [
                    "### Regulatory Risks",
                    "",
                ]
            )
            for risk in protocol_map.regulatory_risks:
                lines.append(f"- ⚠️ {risk}")
            lines.append("")

        return lines

    def _format_footer(self) -> list[str]:
        return [
            "---",
            "",
            "*Report generated by Solstein Market Protocol Mapper*",
            "",
            "**Methodology:** Protocol detection uses country and market signal matching "
            "against known European energy market frameworks. Coverage may be incomplete "
            "for companies with limited public disclosure.",
        ]


class BatchProtocolReportGenerator(ProtocolReportGenerator):
    def __init__(self):
        self.generator = ProtocolReportGenerator()

    def generate_batch(
        self,
        results: list[tuple[str, ProtocolMap]],
        output_dir: Path,
    ) -> list[Path]:
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []

        for company_name, protocol_map in results:
            safe_name = company_name.replace(" ", "_")
            report_path = output_dir / f"{safe_name}_protocols.md"
            report_content = self.generator.generate(protocol_map)
            report_path.write_text(report_content, encoding="utf-8")
            paths.append(report_path)

        return paths



    async def generate_narratives(
        self,
        protocol_map: ProtocolMap,
        industry: str = "energy software",
        region: str = "Europe",
    ) -> dict[str, str]:
        from .narrative_synthesis import NarrativeContext, NarrativeSynthesisEngine
        context = NarrativeContext(
            company_name=protocol_map.company_name,
            industry=industry,
            region=region,
            data_quality="medium",
        )
        engine = NarrativeSynthesisEngine()
        return await engine.generate_protocol_narrative(protocol_map, context)

    def generate_with_narratives(
        self, protocol_map: ProtocolMap, narratives: dict[str, str]
    ) -> str:
        lines = [
            f"# Market Protocol Mapping - {protocol_map.company_name}",
            "",
            "*Generated by Solstein Market Protocol Mapper (Epic 4)*",
            "",
            "---",
            "",
            narratives.get("market_entry_narrative", ""),
            "",
            "## Market Presence Overview",
            "",
        ]
        lines.extend(self._format_overview(protocol_map))
        lines.append("")
        lines.extend(self._format_markets(protocol_map))
        lines.append("")
        lines.extend(self._format_strategy(protocol_map))
        lines.append("")
        lines.append(narratives.get("expansion_analysis", ""))
        lines.append("")
        lines.extend(self._format_footer())
        return "\n".join(lines)
